# Generated by Django 6.0.1 on 2026-01-18 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('lives', models.PositiveSmallIntegerField(default=3)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('challenge_day', models.PositiveIntegerField(default=1)),
                ('is_rogue', models.BooleanField(default=False)),
                ('joined_challenge_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rogue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
