# Generated by Django 6.0.1 on 2026-01-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('standard', 'Standard'), ('crushing', 'Crushing')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
