# Generated by Django 6.0.1 on 2026-03-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_last_closed_ist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_closed_ist_date',
        ),
    ]
