# Generated by Django 6.0.1 on 2026-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_last_closed_ist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_closed_ist_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
