# Generated by Django 6.0.1 on 2026-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('days', models.PositiveIntegerField(help_text='Number of days for this level')),
                ('number_of_questions', models.PositiveIntegerField(help_text='Expected number of questions for this level')),
            ],
            options={
                'verbose_name_plural': 'Difficulties',
            },
        ),
    ]
