# Generated by Django 6.0.1 on 2026-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='mode_name',
            field=models.CharField(default='Easy', max_length=50),
        ),
    ]
