# Generated by Django 6.0.1 on 2026-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_difficulty_mode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='logo',
            field=models.TextField(blank=True, help_text='SVG logo content', null=True),
        ),
    ]
