"""
Django settings for rogue_code_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env files (first wins for duplicate keys). See GOOGLE_OAUTH_CLIENT_ID below.
_ENV_FILES = [
    BASE_DIR / ".env",  # rogue_code_backend/.env
    BASE_DIR.parent / ".env",  # monorepo root .env
    BASE_DIR.parent / "rogue_code_frontend" / ".env",  # same Client ID often lives here as VITE_*
]
try:
    from dotenv import load_dotenv

    for _env_path in _ENV_FILES:
        if _env_path.is_file():
            load_dotenv(_env_path, override=False)
except ImportError:
    pass

# Google Sign-In: Web Client IDs from env (same value from Google Cloud; often duplicated as VITE_* and GOOGLE_*).
# Order: VITE first — the ID token's `aud` matches the client ID used in the browser (VITE_GOOGLE_CLIENT_ID).
_GOOGLE_OAUTH_IDS: list[str] = []
for _key in ("VITE_GOOGLE_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_ID"):
    _v = (os.environ.get(_key) or "").strip()
    if _v and _v not in _GOOGLE_OAUTH_IDS:
        _GOOGLE_OAUTH_IDS.append(_v)
GOOGLE_OAUTH_CLIENT_IDS = _GOOGLE_OAUTH_IDS
GOOGLE_OAUTH_CLIENT_ID = _GOOGLE_OAUTH_IDS[0] if _GOOGLE_OAUTH_IDS else ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ce!s0jnf6%q!9y4l52lhncm=w)76m09#(h9d2831v$6@65oiui'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'rest_framework',
    'corsheaders',
]

CORE_APPS = [
    'apps.accounts',
    'apps.profiles',
    'apps.challenges',
    'apps.evaluator',
    'apps.common',
    'apps.compiler',
]

INSTALLED_APPS += EXTERNAL_APPS + CORE_APPS

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Default display / naive-datetime interpretation. DB still stores UTC when USE_TZ=True.
# Day-boundary business logic (e.g. midnight rollover): use Asia/Kolkata explicitly (IST).
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.auth.CustomJWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "apps.common.exception_handler.custom_exception_handler",
}



# JWT
from datetime import timedelta

SIMPLE_JWT = {
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


#Email config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "devathwani461@gmail.com"
EMAIL_HOST_PASSWORD = "wczk wfai xmlx wywq"

# Frontend config
FRONTEND_URL = "http://localhost:5173"

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
