# Generated by Django 6.0.1 on 2026-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='return_type',
            field=models.CharField(max_length=100),
        ),
    ]
