# Generated by Django 6.0.1 on 2026-02-21 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_question_return_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='return_type',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='QuestionParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type_schema', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='challenges.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='challenges.question')),
            ],
        ),
    ]
