# Generated by Django 6.0.1 on 2026-02-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_question_is_active_remove_question_parameters_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='common.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('question_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='challenges.questionplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('question_plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='challenges.dailyplan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('daily_plan', 'question')},
            },
        ),
    ]
