# Generated by Django 6.0.1 on 2026-02-22 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_questionplan_dailyplan_dailyplanitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
